#!/bin/bash
#SBATCH -A PHY20010
#SBATCH -p development
#SBATCH -t 02:00:00
#SBATCH -N 1 -n 56
#SBATCH -J Ising2D_run
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lorenzo.ennoggi@gmail.com
#SBATCH -o Ising2D_run.out
#SBATCH -e Ising2D_run.err

echo "Begin"
date
time ibrun ./Ising2D_exe
##time ibrun -l vtune -quiet -collect hpc-performance -trace-mpi -result-dir vtune_analysis ./Ising2D_exe
echo "Done"
date
