#!/bin/bash
#SBATCH -p gp-default
#SBATCH -t 48:00:00
#SBATCH -N 1 -n 16
#SBATCH -J Ising2D_run
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lorenzo.ennoggi@gmail.com
#SBATCH -o Ising2D_run.out
#SBATCH -e Ising2D_run.err

module restore intel2021

# This only works with less MPI processes than physical cores, except if only using one node 
##time srun --mpi=pmix ./Ising2D_exe

echo "Begin"
date
time mpirun -mca btl self,vader ./Ising2D_exe
echo "Done"
date
