#!/bin/bash
#SBATCH -A cin_staff
#SBATCH -p boost_fua_dbg
#SBATCH --qos=normal
#SBATCH -t 00:10:00
#SBATCH -N 1 -n 4
#SBATCH --gres=gpu:4  # 4 GPUs per node (matches the actual hardware on Pitagora)
#SBATCH --mem=0
#SBATCH -J Ising2D_run
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lorenzo.ennoggi@gmail.com
#SBATCH -o Ising2D_run.out
#SBATCH -e Ising2D_run.err

# =========================================================
# Refer to Pitagora's documentation at
#   https://docs.hpc.cineca.it/hpc/pitagora.html
# for partition (-p) and quality of service (--qos) options
# =========================================================

echo "Begin"
date
time srun ./Ising2D_exe
##time srun -l vtune -quiet -collect hpc-performance -trace-mpi -result-dir vtune_analysis ./Ising2D_exe
echo "Done"
date
