name: CI

on:
    push:
    pull_request:

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            - name: Compile the code
              run:  make -j4 options=OptionLists/Ubuntu_GNU_CI.cfg
